### ISSUE TITLE
Plugin Inside Docker Not Allowing To Connect

### ISSUE THREAD

**Issue by munawarb** [ForgeRock/es-change-feed-plugin#10]
We're running this plugin inside docker alongside ElasticSearch. The plugin log shows that it's listening on 0.0.0.0:9400, but when we try to connect to the websocket endpoint, the connection is closed. Is there a special configuration we need to connect to the exposed websocket endpoint?

**Comment by jurgc11** [comment]
There's no special configuration you need. Are you trying to connect from within the container or from outside? I'd recommend putting a websocket client in the container and trying to connect that way so you can rule out any docker oddness.

**Comment by SymphoniAdmin** [comment]
Hi @jurgc11  iam trying from outside via websocket client ..but it is not connecting..could you  please help me in this.

**Comment by snaimuddin** [comment]
Hi @jurgc11 iam trying from outside via websocket client ..but it is not connecting..could you please help me in this.

**Comment by snaimuddin** [comment]
@jurgc11 we have change any configuration in elasticsearch.yml regarding port number ?

**Comment by jurgc11** [comment]
You don't need to provide any configuration if you're happy with the defaults. The default port is 9400

**Comment by snaimuddin** [comment]
@jurgc11  Thank you for reply..
But Connection is opening...when i seee the logs Websocker socket server started..

**Comment by snaimuddin** [comment]
@jurgc11  what will be the endpoint to open a websocket connection ?

**Comment by jurgc11** [comment]
It's /ws/_changes

**Comment by snaimuddin** [comment]
Hi i did in the same way

ws://localhost:9400/ws/_changes

But it didnt connect..

________________________________________

**Comment by crispibits** [comment]
What tool are you using to connect?

Have you tried using the hostname rather than localhost?

Have you confirmed the port is open, eg:
nc -v localhost 9400
or
nc -v $(hostname) 9400

**Comment by snaimuddin** [comment]
HI @jurgc11 
Am using online Websocket client 
https://www.websocket.org/echo.html
and
Chrome websocket Client
when i tried nc -v localhost 9400 it says
Ncat:Version 6.40 (http://nmap.org/ncat)
Ncat: Connected to 127.0.0.1:9400

But Still Not able to connect...

**Comment by snaimuddin** [comment]
@jurgc11 @crispibits 
Hi guys
it works me after flushing out my dns...Thank you
But the ES and plugin is running in Marathon and the Websoket server also started ,but he am not able to open websocket connection from Mozilla websocket client..
