### ISSUE TITLE
cant able to install plugin to elasticsearch version 5.3.2

### ISSUE THREAD

**Issue by snaimuddin** [ForgeRock/es-change-feed-plugin#11]
Hi  guys
iam not able to install es-change-feed-plugin for the elasticsearch version of 5.3.2
it says as follows:
ERROR:'elasticsearch' directory is missing in the plugin zip.
please help me.

**Comment by jurgc11** [comment]
How are you installing the plugin?

**Comment by snaimuddin** [comment]
Hi @jurgc11 
using the following command:
bin/plugin install -b https://github.com/jurgc11/es-change-feed-plugin/releases/download/v5.3.2/es-changes-feed-plugin.zip

**Comment by snaimuddin** [comment]
bin/elasticsearch-plugin  install -b https://github.com/jurgc11/es-change-feed-plugin/releases/download/{version}/es-changes-feed-plugin.zip

**Comment by snaimuddin** [comment]
HI @jurgc11 
using the following command

bin/elasticsearch-plugin install -b https://github.com/jurgc11/es-change-feed-plugin/releases/download/v5.3.2/es-changes-feed-plugin.zip

**Comment by jurgc11** [comment]
Looks like the build for 5.3.2 is broken. If you can, use 5.4.0, otherwise we'll need to create a new build of 5.3.2

**Comment by snaimuddin** [comment]
i had installed this plugin to the elasticsearch version of v5.4.2 successfully.But the reason am downgrading 
is compatability version of kibana  v5.4.2 is not supporting.

**Comment by snaimuddin** [comment]
i had installed this plugin to the elasticsearch version of v5.4.0 successfully.But the reason am downgrading
is compatability version of kibana v5.4.0 is not supporting.

**Comment by snaimuddin** [comment]
Hi @jurgc11 
please create a new build of 5.3.2 version,it will be great for us if you do this.

**Comment by snaimuddin** [comment]
Hi @jurgc11 ok .please share the instructions ,i will try to build it.
Thanks.

**Comment by snaimuddin** [comment]
HI @jurgc11   any update ,please let me know

**Comment by snaimuddin** [comment]
Hi @jurgc11  ,did you got time to build a latest version of es-change-feef-plugin ? for the compate version of 5.3.2 .

**Comment by jurgc11** [comment]
I've built 5.3.2 again, could you let me know how you get on with it?

**Comment by snaimuddin** [comment]
Hi @jurgc11  i had installed es-feed plugin for version 5.3.2 elasticsearch,and it is working now.
Thank you for latest build.
