### ISSUE TITLE
unknown data receiving

### ISSUE THREAD

**Issue by snaimuddin** [ForgeRock/es-change-feed-plugin#13]
HI Team 
am sending data to elasticsearch and am receiving data through websocket plugin ,along with that am receiving unknown data also which is am not sending to elasticsearch.
the following data am receiving but am not sending this to elasticsearch 
{"_index":".monitoring-es-2-2018.04.10","_type":"shards","_id":"uw4w5-TdTyipDcj5gFgG4Q:_na:logs:1:r","_timestamp":"2018-04-10T08:45:33.256Z","_version":451,"_operation":"INDEX","_source"::)
please help me in this

**Comment by snaimuddin** [comment]
Hi guys
after i debug the things,i found that the elasticsearch internally creates so many indexes and pushing data to elasticsearch ,for example information about cluster ,shards ,kibana etc ..
is there a way that i can receive to my websokcet the logs which belongs to particulat index ?

**Comment by snaimuddin** [comment]
Hi team
i need a  websocket url. which is to get data of index "logs"..in my elasticsearch  ,index name is "logs" ,in this index am pushing data and i want data from that index only..

**Comment by jurgc11** [comment]
Take a look at the documentation, specifically https://github.com/ForgeRock/es-change-feed-plugin#changeslistensource
