### ISSUE TITLE
ES5+ Site Plugins / elasticsearch directory is missing in the plugin zip

### ISSUE THREAD

**Issue by szorg** [ForgeRock/es-change-feed-plugin#7]
It looks like this might just not be compatible in its current form with ES5+.. I'm not sure if this was accounted for with your new releases, but they no longer support site plugins which causes errors like this, with built versions and with downloaded binaries:

Alternatively of course I don't know what the heck I'm doing.. any suggestions here, if that might be the case? 

$ sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///tmp/es-changes-
feed-plugin.zip
-> Downloading file:///tmp/es-changes-feed-plugin.zip
[=================================================] 100%  
ERROR: `elasticsearch` directory is missing in the plugin zip

**Comment by jurgc11** [comment]
This isn't a site plugin, so isn't affected by the removal of site plugin support in ES 5.x. I'm not sure why the way you're installing it doesn't work, but if you follow the docs you shouldn't have any problems:
https://github.com/ForgeRock/es-change-feed-plugin#prebuilt-binary-installation
