### ISSUE TITLE
Whenever i create or update the document in ES, I get DELETE notification first

### ISSUE THREAD

**Issue by codeforgeek** [ForgeRock/es-change-feed-plugin#9]
Received: {"_index":"liferay-20116","_type":"LiferayDocumentType","_id":"com.liferay.journal.model.JournalArticle_PORTLET_37798","_timestamp":"2017-10-06T09:03:12.369Z","_version":7,"_operation":"DELETE"}

Then,

Received: {"_index":"liferay-20116","_type":"LiferayDocumentType","_id":"com.liferay.journal.model.JournalArticle_PORTLET_37798","_timestamp":"2017-10-06T09:03:12.377Z","_version":8,"_operation":"CREATE","_source":{"ddmTemplateKey":"31315","ddm__keyword__31312__Id_fr_FR_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","entryClassPK":"37799","ddm__keyword__31312__Id_en_US_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Image_nl_NL_sortable":"","publishDate":"20170706090300","ddm__keyword__31312__Id_nl_NL_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Id_iw_IL":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Image_ja_JP_sortable":"","ddm__keyword__31312__Image_en_US":"","classNameId":"0","ddm__keyword__31312__Image_ja_JP":"","ddm__keyword__31312__Image_de_DE_sortable":"","modified_sortable":1507280597917,"ddm__keyword__31312__Image_fr_FR_sortable":"","ddm__keyword__31312__Image_ca_ES_sortable":"","ddm__keyword__31312__Id_fi_FI":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Id_ca_ES_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Image_iw_IL_sortable":"","priority":"0.0","version":"1.0","ddm__keyword__31312__Image_fr_FR":"","ddm__keyword__31312__Image_en_US_sortable":"","ddm__keyword__31312__Id_ja_JP_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Image_zh_CN":"","title_en_US":"Mumbai","status":"0","ddm__keyword__31312__Id_hu_HU":"f2903213-841a-4951-b0d9-494e842a25c5","articleId_sortable":"37797","publishDate_sortable":1499331780000,"ddm__keyword__31312__Id_zh_CN_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","priority_sortable":0.0,"ddm__keyword__31312__Id_iw_IL_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Id_es_ES_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","uid":"com.liferay.journal.model.JournalArticle_PORTLET_37798","ddm__keyword__31312__Id_nl_NL":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Image_zh_CN_sortable":"","title_sortable":"mumbai","assetTagNames":"layoutwebpartpage","layoutUuid":"","createDate":"20171006090317","displayDate_sortable":1499331780000,"entryClassName":"com.liferay.journal.model.JournalArticle","ddm__keyword__31312__Id_pt_BR_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","userId":"20156","ddm__keyword__31312__Id_fi_FI_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Id_de_DE_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","treePath":["","37775"],"ddm__keyword__31312__Id_de_DE":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Id_ja_JP":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Id_fr_FR":"f2903213-841a-4951-b0d9-494e842a25c5","ratings_sortable":0.0,"groupId":"20143","createDate_sortable":1507280597822,"classPK":"0","scopeGroupId":"20143","modified":"20171006090317","ddm__keyword__31312__Image_nl_NL":"","content_en_US":"f2903213-841a-4951-b0d9-494e842a25c5","visible":"true","ddmStructureKey":"31311","assetTagIds":"37779","defaultLanguageId":"en_US","viewCount_sortable":0,"ddm__keyword__31312__Image_hu_HU":"","ddm__keyword__31312__Image_fi_FI_sortable":"","folderId":"37775","classTypeId":"31312","companyId":"20116","rootEntryClassPK":"37799","displayDate":"20170706090300","description_en_US":"Mumbai","ddm__keyword__31312__Id_zh_CN":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Id_ca_ES":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Image_es_ES_sortable":"","ddm__keyword__31312__Image_hu_HU_sortable":"","ddm__keyword__31312__Id_pt_BR":"f2903213-841a-4951-b0d9-494e842a25c5","description":"Mumbai","ddm__keyword__31312__Image_fi_FI":"","title":"Mumbai","content":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Id_hu_HU_sortable":"f2903213-841a-4951-b0d9-494e842a25c5","head":"true","ratings":"0.0","expirationDate_sortable":9223372036854775807,"viewCount":"0","ddm__keyword__31312__Id_es_ES":"f2903213-841a-4951-b0d9-494e842a25c5","expirationDate":"99950812133000","ddm__keyword__31312__Image_es_ES":"","ddm__keyword__31312__Image_pt_BR_sortable":"","roleId":"20124","articleId":"37797","ddm__keyword__31312__Image_iw_IL":"","userName":"test test","ddm__keyword__31312__Id_en_US":"f2903213-841a-4951-b0d9-494e842a25c5","ddm__keyword__31312__Image_de_DE":"","ddm__keyword__31312__Image_ca_ES":"","localized_title_zh_CN":"mumbai","localized_title_zh_CN_sortable":"mumbai","localized_title_es_ES":"mumbai","localized_title_es_ES_sortable":"mumbai","localized_title_ja_JP":"mumbai","localized_title_ja_JP_sortable":"mumbai","localized_title_iw_IL":"mumbai","localized_title_iw_IL_sortable":"mumbai","localized_title_nl_NL":"mumbai","localized_title_nl_NL_sortable":"mumbai","localized_title_fi_FI":"mumbai","localized_title_fi_FI_sortable":"mumbai","localized_title_ca_ES":"mumbai","localized_title_ca_ES_sortable":"mumbai","localized_title_hu_HU":"mumbai","localized_title_hu_HU_sortable":"mumbai","localized_title_fr_FR":"mumbai","localized_title_fr_FR_sortable":"mumbai","localized_title":"mumbai","localized_title_en_US":"mumbai","localized_title_en_US_sortable":"mumbai","localized_title_pt_BR":"mumbai","localized_title_pt_BR_sortable":"mumbai","localized_title_de_DE":"mumbai","localized_title_de_DE_sortable":"mumbai","ddm__keyword__31312__Image_pt_BR":"","stagingGroup":"false","headListable":"true"}}

Same behaviour for delete and update.

**Comment by jurgc11** [comment]
What's your question/problem?

**Comment by jurgc11** [comment]
Sorry, I missed the title. I think this must be a problem with how you're updating the document. If you look in the messages you can see the first message has version 7 and the second has version 8, so that's actually 2 changes as far as Elasticsearch is concerned. When I update a doc in Elasticsearch, I just get a single new version. If you're using a some kind of Elasticsearch client, i'd take a look at that.
